spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: postgresql
        url: jdbc:postgresql://localhost:5432/employee_management_admininstration_service
        username: postgres
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
