spring:
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            routes:
                - id: administration-service
                  uri: lb://administration-service
                  predicates:
                      - Path=/admin/**
                  filters:
                      - RemoveRequestHeader=Cookie,Set-Cookie
                - id: payment-log-service
                  uri: lb://payment-log-service
                  predicates:
                      - Path=/payments/**
                - id: task-service
                  uri: lb://task-service
                  predicates:
                      - Path=/tasks/**
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
