spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
          hibernate:
              jdbc:
                lob:
                    non_contextual_creation: true
              format_sql: true
logging:
    level:
      org:
          hibernate:
              type:
                  descriptor:
                      sql: trace
